<a href="https://colab.research.google.com/github/8persy/algoritms_colab/blob/main/%22%D0%97%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D0%B54_11_311_%D0%A1%D0%BE%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B8_%D0%B8_%D0%BF%D0%BE%D0%B8%D1%81%D0%BA_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Сортировка и поиск**

**Сортировка массивов** часто используется в программировании, чтобы помочь понять данные и выполнить поиск. Поэтому скорость сортировки больших объемов информации крайне важна для функциональных проектов и оптимизации времени работы

<img src="https://habrastorage.org/getpro/habr/upload_files/441/cf4/f42/441cf4f426f3f0b22883bdcdd81d2904.png"/>

In [ ]:
import numpy as np

## Сортировка вставками

**Алгоритм сортировки:**

1. Начинаем работу со второго элемента массива
2. Запоминаем значение второго элемента массива
3. Сравниваем каждый предыдущий элемент массива с текущим и, при необходимости, меняем их местами до тех пор, пока не дойдем до начала цикла или пока не встретится элемент менее текущего
4. В результате массив отсортируется по возрастанию.

<img src="https://media.proglib.io/wp-uploads/-000//1/596b723189cb1_Zmjm3wv.gif"/>

### Чекпоинт 1

Реализовать функцию, сортирующую массив с помощью сортировки вставками

In [ ]:
def insertion_sort(array):
  for i in range(1, len(array)):
    for j in range(i, 0, -1):
      if array[j-1] > array[j]:
        array[j], array[j-1] = array[j-1], array[j]
      else:
        break
  return array

In [ ]:
array = np.array([3, 1, 7, 4, 6, 8, 2, 5])
insertion_sort(array)
array

array([1, 2, 3, 4, 5, 6, 7, 8])

### Сложность сортировки вставками


*   Лучший случай = $O(N)$
*   Худший случай = $O(N^2)$

*   Сложность по памяти = $O(1)$







## Сортировка выбором

**Алгоритм сортировки:**

1. В неотсортированном подмассиве ищется локальный максимум (минимум).
2. Найденный максимум (минимум) меняется местами с последним (первым) элементом в подмассиве.
3. Если в массиве остались неотсортированные подмассивы — смотри пункт 1.

<img src="https://media.proglib.io/wp-uploads/-000//1/596b722fd2a7d_djIHfUK.gif"/>

### Чекпоинт 2


Реализовать функцию, сортирующую массив с помощью сортировки выбором

In [ ]:
def selection_sort(array):
  left = 0
  while left < len(array):
    min = left
    for i in range(left, len(array)):
      if array[i] < array[min]:
        min = i
    array[left], array[min] = array[min], array[left]
    left += 1
  return array

In [ ]:
array = np.array([3, 1, 7, 4, 6, 8, 2, 5])
selection_sort(array)
array

array([1, 2, 3, 4, 5, 6, 7, 8])

### Сложность сортировки выбором


*   Лучший случай = $O(N^2)$
*   Худший случай = $O(N^2)$

*   Сложность по памяти = $O(1)$

## Сортировка слиянием

**Алгоритм сортировки:**
1. Разбиваем массив на две части примерно одинакового размера
2. Сортируем каждую из получившихся частей (также сортировкой слиянием (до тех пор пока массив не станет длины 1))
3. Два упорядоченных массива половинного размера соединяются в один

<img src="https://media.proglib.io/wp-uploads/-000//1/596b722dc99d1_3qHz285.gif"/>

### Чекпоинт 3


Реализовать функцию, сортирующую массив с помощью сортировки слиянием

In [ ]:
def merge_sort(arr: np.ndarray | list):
    middle = len(arr) // 2
    if middle > 0:
        arr1 = merge_sort(arr[:middle])
        arr2 = merge_sort(arr[middle:])
        return merge2_sort(arr1, arr2)
    else:
        return arr


def merge2_sort(arr1, arr2):
    res_arr = []
    i1 = 0
    i2 = 0
    while i1 < len(arr1) and i2 < len(arr2):
        if arr1[i1] < arr2[i2]:
            res_arr.append(arr1[i1])
            i1 += 1
        else:
            res_arr.append(arr2[i2])
            i2 += 1
    if i1 == len(arr1):
        res_arr.extend(arr2[i2:])
    else:
        res_arr.extend(arr1[i1:])

    return res_arr


In [ ]:
array = np.array([3, 1, 7, 4, 6, 8, 2, 5])
print(merge_sort(array))
array


[1, 2, 3, 4, 5, 6, 7, 8]


array([3, 1, 7, 4, 6, 8, 2, 5])

### Сложность сортировки слиянием

*   Лучший случай = $O(N * log N)$
*   Худший случай = $O(N * log N)$

*   Сложность по памяти = $O(N)$

## Бинарный поиск

**Алгоритм поиска:**

1. Сортируем массив (для бинарного поиска это важно)
2. Определяем значение элемента в середине массива. Полученное значение сравнивается с тем, что нам нужно найти
3. Если искомый элемент меньше значения середины, то поиск осуществляется в первой половине элементов, иначе — во второй
4. Поиск сводится к тому, что вновь определяется значение серединного элемента в выбранной половине и сравнивается с искомым значением
5. Процесс продолжается до тех пор, пока не будет найден элемент со значением искомого элемента или не станет пустым интервал для поиска

![binary_search](https://habrastorage.org/r/w1560/getpro/habr/post_images/d99/286/22b/d9928622b0685e9fa1e77ce4d9117694.png)


### Чекпоинт 4

Реализовать бинарный поиск, используя любую реализованную сортировку выше

In [ ]:
def binary_search():
  pass

In [ ]:
array = np.array([3, 1, 7, 4, 6, 8, 2, 5])

In [ ]:
binary_search(array, 9)

In [ ]:
binary_search(array, 2)

### Сложность бинарного поиска

*   Лучший случай = $O(log N)$
*   Худший случай = $O(log N)$

*   Сложность по памяти = $O(1)$

## Сортировка TimSort

Идея сортировки:



*   Массивы реальных данных часто содержат в себе упорядоченные выборки данных
*   Состоит их сортировки вставками и сортировки слиянием
*   Принудительное разбиение на упорядоченные подмассивы (run'ы)




Что такое run?

Run - наименьшее разбиение отсортированных подмассивов для дальнейшего слияния

Tim определил, что лучше всего делить на подмассивы с размером от 32 до 64, так как при наиболее маленьких массивах получается слишком много массивов, которые необходимо объединить, а при run'е больше 64 сортировка вставками будет долго работать, так как в худжем случае ее сложность равна $O(N^2)$

!И при этом run'ы должны быть степенью двойки

### Сложность TimSort

*   Лучший случай = $O(N)$
*   Худший случай = $O(N * log N)$

*   Сложность по памяти = $O(N)$

In [ ]:
array.sort()
array

array([1, 2, 3, 4, 5, 6, 7, 8])